<?php

namespace AppBundle\Repository\User\Client;

/**
 * CompanyUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyUserRepository extends \Doctrine\ORM\EntityRepository
{
}
