<?php

namespace AppBundle\Repository\Media;

/**
 * DistantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistantRepository extends \Doctrine\ORM\EntityRepository
{
}
