security:
    encoders:
        AppBundle\Entity\User\User: bcrypt

    providers:
        in_memory:
            memory: ~

        user_provider:
            entity:
                class: AppBundle:User\User
                property: userName

    firewalls:
        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            provider: user_provider
            json_login:
                check_path: /login_check
                username_path: userName
                password_path: pwd
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: user_provider
            http_basic: ~
            stateless: true
            anonymous: true
            lexik_jwt: ~

    access_control:
         - { path: ^/models, roles: ROLE_ADMIN }
