# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Action\:
        resource: '../../src/AppBundle/Action'
        public: true
        tags: ['controller.service_arguments']

    AppBundle\Serializer\Normalizer\Product:
        decorates: 'api_platform.jsonld.normalizer.item'
        public: false
        tags: [serializer.normalizer]
        arguments: [ '@AppBundle\Serializer\Normalizer\Product.inner' ]

    AppBundle\Serializer\Normalizer\Model:
        decorates: 'api_platform.jsonld.normalizer.item'
        public: false
        tags: [serializer.normalizer]
        arguments: [ '@AppBundle\Serializer\Normalizer\Model.inner' ]

    AppBundle\Serializer\Normalizer\Company:
        decorates: 'api_platform.jsonld.normalizer.item'
        public: false
        tags: [serializer.normalizer]
        arguments: [ '@AppBundle\Serializer\Normalizer\Company.inner' ]

    AppBundle\Serializer\Normalizer\Client:
        decorates: 'api_platform.jsonld.normalizer.item'
        public: false
        tags: [serializer.normalizer]
        arguments: [ '@AppBundle\Serializer\Normalizer\Client.inner' ]

    AppBundle\Serializer\Normalizer\Partner:
        decorates: 'api_platform.jsonld.normalizer.item'
        public: false
        tags: [serializer.normalizer]
        arguments: [ '@AppBundle\Serializer\Normalizer\Partner.inner' ]

    AppBundle\Serializer\Normalizer\Brand:
        decorates: 'api_platform.jsonld.normalizer.item'
        public: false
        tags: [serializer.normalizer]
        arguments: [ '@AppBundle\Serializer\Normalizer\Brand.inner' ]

    AppBundle\Serializer\Normalizer\Family:
        decorates: 'api_platform.jsonld.normalizer.item'
        public: false
        tags: [serializer.normalizer]
        arguments: [ '@AppBundle\Serializer\Normalizer\Family.inner' ]

    user_listener:
            class: AppBundle\EventListener\UserListener
            tags:
                - { name: doctrine.orm.entity_listener }
                - { name: doctrine.orm.entity_listener, entity_manager: custom }

#    'AppBundle\Swagger\SwaggerDecorator':
#        decorates: 'api_platform.swagger.normalizer.documentation'
#        arguments: [ '@AppBundle\Swagger\SwaggerDecorator.inner' ]
#        autoconfigure: false


    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'
