<?php

namespace AppBundle\Repository\Product;

/**
 * FamilyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilyRepository extends \Doctrine\ORM\EntityRepository
{

    public function getProducts($id){

        // DQL statement fetching all brand's products
        $state = "
            SELECT p
            FROM AppBundle:Product\Product p
            JOIN p.model m
            JOIN m.family f 
            WHERE f.id = :family_id
        ";

        // Execute the query and store results
        $models = $this->getEntityManager()
            ->createQuery($state)
            ->setParameter('family_id', $id)
            ->getResult();

        // Return the products
        return $models;

    }
}
