<?php

namespace AppBundle\Repository\Guarantee;

/**
 * ClauseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClauseRepository extends \Doctrine\ORM\EntityRepository
{
}
