<?php

namespace AppBundle\Repository\Feature;

/**
 * ModelFeatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelFeatureRepository extends \Doctrine\ORM\EntityRepository
{
}
