<?php

namespace AppBundle\Repository\Feature;

/**
 * ProductTestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductTestRepository extends \Doctrine\ORM\EntityRepository
{
}
