<?php

namespace AppBundle\Repository\Feature;

/**
 * SpecRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecRepository extends \Doctrine\ORM\EntityRepository
{
}
