<?php

namespace AppBundle\Repository\Feature;

/**
 * SpecValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecValueRepository extends \Doctrine\ORM\EntityRepository
{
}
