resources:
  AppBundle\Entity\Product\Family:
    collectionOperations:
      family_list:
        method: GET
        path: /families
        normalization_context:
          groups: ['family_list']
        swagger_context:
          responses:
            201:
              description: Get Family resources collection
              schema:
                type: array
                items:
                  $ref: '#/definitions/Family-family_list'
            401:
              description: Bad credentials, check authentication and authorization
            404:
              description: Resource not found
    itemOperations:
      family_show:
        method: GET
        path: /families/{id}
        normalization_context:
          groups: ['family_show']
        swagger_context:
          summary: Retrieve one Family resource
          description: Retrieve Family resource with given id param
          parameters:
            0:
              name: id
              type: integer
              description: Family's resource id you want to reach
          responses:
            201:
              description: Get specific Family resource related to given id paramameter
              schema:
                $ref: '#/definitions/Family-family_show'
            401:
              description: Bad credentials, check authentication and authorization
            404:
              description: Resource not found
      family_models:
        method: GET
        path: /families/{id}/models
        normalization_context:
          groups: ['family_models']
        swagger_context:
          summary: Retrieve Family Models subresources
          description: Retrieve Family Models subresource with given id param
          parameters:
            0:
              name: id
              type: integer
              description: Family's Models subresource id you want to reach
          responses:
            201:
              description: Get specific Family's Models subresource related to given id paramameter
              schema:
                $ref: '#/definitions/Family-family_models'
            401:
              description: Bad credentials, check authentication and authorization
            404:
              description: Resource not found
      family_products:
        route_name: family_products
        normalization_context:
          groups: ['family_products']
        swagger_context:
          summary: Retrieve Family Products subresources
          description: Retrieve Family Products subresource with given id param
          parameters:
            0:
              name: id
              type: integer
              description: Family's Products subresource id you want to reach
          responses:
            201:
              description: Get specific Family's Products subresource related to given id paramameter
              schema:
                $ref: '#/definitions/Family-family_products'
            401:
              description: Bad credentials, check authentication and authorization
            404:
              description: Resource not found
