resources:
  AppBundle\Entity\User\Partner:
    collectionOperations:
      partner_list:
        method: GET
        path: /partners
        normalization_context:
          groups: ['partner_list']
        swagger_context:
          responses:
            201:
              description: Get Partner resources collection
              schema:
                type: array
                items:
                  $ref: '#/definitions/Partner-partner_list'
      partner_create:
        method: POST
        denormalization_context:
          groups: ['partner_create']
        normalization_context:
          groups: ['partner_list']
        swagger_context:
          summary: Allow to add new Partner user in DB
          description: Create new Partner user
    itemOperations:
      partner_show:
        method: GET
        path: /partners/{id}
        normalization_context:
          groups: ['partner_show']
        swagger_context:
          summary: Retrieve one Partner resource
          description: Retrieve Partner resource with given id param
          parameters:
            0:
              name: id
              type: integer
              description: Partner's resource id you want to reach
          responses:
            201:
              description: Get specific Partner resource related to given id paramameter
              schema:
                $ref: '#/definitions/Partner-partner_show'