Iphone 6s seconde main:
    model_name: Iphone 6s
    description: Très bon état général, micro-rayures au dos de l'appareil.
    price: 200
    sellState: used
    physicState: good
    available: true
    history: A appartenu à un particulier. Pas de trace de réparation.
    IMEI: "123456789012347"
    memorySizeInGb: 32
    operatorLock: false
    color: Noir&Ardoise
    systemVersion: 11
    formatted: formatted
    softStatus: boot_properly

Iphone X neuf:
    model_name: Iphone X
    description: Appareil neuf avec boite d'origine, encore sous blister
    price: 1400
    sellState: new
    physicState: unused
    available: true
    history: null
    IMEI: "123456789012348"
    memorySizeInGb: 256
    operatorLock: false
    color: Noir&Ardoise
    systemVersion: 11
    formatted: formatted
    softStatus: boot_properly

Iphone 5 accidenté:
    model_name: Iphone 5
    description: Appareil abimé avec écran cassé et caméra avant HS
    price: 80
    sellState: defective
    physicState: bad
    available: true
    history: A chuté mais ne présente pas de traces d'oxydation
    IMEI: "123456789012342"
    memorySizeInGb: 16
    operatorLock: false
    color: Noir&Ardoise
    systemVersion: 10.3.3
    formatted: not_formatted
    softStatus: boot_properly
    notices:
        info: Le téléphone n'a pas été réinitialisé et demande un code de déverouillage, qui ne nous a pas été
              communiqué
    tests:
        main_camera:
            phyDamage: false
            isWorking: false
            message: La lentille ne présente pas de rayure ou de cassure et le hublot de protection n'est pas abimé. L'écran
              reste noir au lancement de l'application appareil photo
        screen:
            phyDamage: true
            isWorking: true
            message: L'écran présente plusieurs fissures profondes qui parcourent tout l'écran, pas de dégats au niveau du LCD
    guarantees:
        global:
            guaranteed: true
            lengthInMonth: 0.25
            message: Cette garantie couvre les pièces non mentionnées ci-après
        main_camera:
            guaranteed: false
            lengthInMonth: 0
            message: Caméra HS
        screen:
            guaranteed: false
            lengthInMonth: 0
            message: Écran fissuré

Iphone 5 reconditionné:
    model_name: Iphone 5
    description: Comme neuf, reconditionné par l'atelier BileMo
    price: 140
    sellState: refurb
    physicState: like_new
    available: true
    history: Reconditionné à neuf dans nos locaux, aucun d'historique
    IMEI: "123456789012342"
    memorySizeInGb: 64
    operatorLock: true
    color: Argent
    systemVersion: 10.3.3
    formatted: formatted
    softStatus: boot_properly


Galaxy S4 sous blister:
    title: Galaxy S4
    model_name: Galaxy S4 I9505
    description: Appareil neuf avec boite d'origine, encore sous blister
    price: 200
    sellState: new
    physicState: unused
    available: true
    history: null
    IMEI: "123456789112348"
    memorySizeInGb: 32
    operatorLock: false
    color: Noir
    systemVersion: 5.0.1
    formatted: formatted
    softStatus: boot_properly

GS4 reconditionné à neuf:
    title: Galaxy S4
    model_name: Galaxy S4 I9505
    description: Appareil reconditionné à neuf
    price: 170
    sellState: refurb
    physicState: like_new
    available: true
    history: Un particulier a bénéficié d'une offre de reprise pour ce téléphone dont le LCD était HS.
    IMEI: "128556789112348"
    memorySizeInGb: 16
    operatorLock: false
    color: Blanc
    systemVersion: 4.4
    formatted: formatted
    softStatus: boot_properly

Galaxy Note 2 pour pièces:
    title: Galaxy Note 2 non fonctionnel
    model_name: Galaxy Note 2
    description: Téléphone oxydé non testé, état esthétique parfait
    price: 200
    sellState: defective
    physicState: like_new
    available: true
    history: Téléphone professionnel racheté à une assurance, a subi un sinistre
    IMEI: "123456789112348"
    memorySizeInGb: 32
    operatorLock: false
    color: Noir
    systemVersion: 5.0.1
    formatted: unknow
    softStatus: unknow
    notices:
        alert: Téléphone oxydé
        info: Aucune désoxydation n'a été effectuée, mais le téléphone a été placé non-démonté dans de la silice
          durant 3 jours. BileMo n'a pas tenté de redémarrer l'appareil
