<?php

namespace AppBundle\Repository\User;

/**
 * BilemoUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BilemoUserRepository extends \Doctrine\ORM\EntityRepository
{
}
