<?php

namespace AppBundle\Repository\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    public function findUser(array $criteria){

        $statement = "
            SELECT p
            FROM AppBundle:User\Partner p
            WHERE p.username = :username
        ";

        // Execute the query and store results
        $user = $this->getEntityManager()
            ->createQuery($statement)
            ->setParameter('username', $criteria['username'])
            ->getArrayResult();

        if(count($user) == 0){

            $statement = "
                SELECT c
                FROM AppBundle:User\Client c
                WHERE c.username = :username
            ";

            // Execute the query and store results
            $user = $this->getEntityManager()
                ->createQuery($statement)
                ->setParameter('username', $criteria['username'])
                ->getArrayResult();
        }

        return $user;

    }
}
